language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
services:
  - mongodb
before_script:
  - npm install
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");
script: ./node_modules/mocha/bin/mocha
